---
- name: Check if krew is installed
  command: kubectl-krew version
  register: krew_check
  changed_when: false
  ignore_errors: yes
  environment:
    PATH: "{{ workstation_krew_path }}:{{ ansible_env.PATH }}"
-
  name: Do install and upgrade krew plugins when installed
  when: krew_check.rc == 0
  block:
    -
      name: Install krew plugins
      command: "kubectl-krew install {{ item }}"
      register: krew_install
      changed_when: krew_install.rc == 0 and 'installed' in krew_install.stdout
      environment:
        PATH: "{{ workstation_krew_path }}:{{ ansible_env.PATH }}"
      loop: "{{ workstation_krew_plugins }}"
    -
      name: Upgrade krew plugins
      command: "kubectl-krew upgrade"
      changed_when: false
      environment:
        PATH: "{{ workstation_krew_path }}:{{ ansible_env.PATH }}"
