---
- name: Create binary dir for Mikroways tools
  file:
    path: "{{ mw_workstation_local_install_directory }}"
    state: directory
    mode: '0755'

- name: Install listed packages
  block:
    - name: "Install package {{ item.name }} ({{ item.version }})"
      include: _download.yml
      vars:
        _item: "{{ item }}"
        name: "{{ item.name }}"
        url: "{{item.url | replace('%version%', item.version) }}"
        version: "{{ item.version }}"
        install_directory: "{{ mw_workstation_local_install_directory }}"
        install_command: >-
          {{ item.install_command | replace('%install_directory%',
              mw_workstation_local_install_directory) |
              replace('%version%', item.version) }}
        version_command: >-
          {{ item.version_command | replace('%install_directory%',
              mw_workstation_local_install_directory) |
              replace('%version%', item.version) }}
      when: (mw_workstation_local_packages_only | length == 0) or
        ( mw_workstation_local_packages_only | length > 0 and
          item.name in mw_workstation_local_packages_only )
      loop: "{{ mw_workstation_local_packages }}"
