---
-
  name: Configure proxy
  import_role:
    name: ruzickap.proxy_settings
  become: true
  vars:
    proxy_settings_http_proxy: "{{ mw_proxy_settings_http_proxy }}"
    proxy_settings_ftp_proxy: "{{ mw_proxy_settings_ftp_proxy }}"
    proxy_settings_https_proxy: "{{ mw_proxy_settings_https_proxy }}"
    proxy_settings_no_proxy: "{{ mw_proxy_settings_no_proxy }}"
    proxy_settings_yum_proxy: "{{ mw_proxy_settings_yum_proxy }}"
    proxy_settings_yum_proxy_username: "{{ mw_proxy_settings_yum_proxy_username }}"
    proxy_settings_yum_proxy_password: "{{ mw_proxy_settings_yum_proxy_password }}"
  when: mw_proxy_enabled
  tags:
    - proxy
