---
- name: Update apt packages
  become: true
  block:
    -
      name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    -
      name: Install pip
      package:
        name: python3-pip
        state: present
    -
      name: Install python apt
      pip:
        name: python-apt
        state: present
    -
      name: Add repositories
      apt_repository:
        repo: "{{ item }}"
      loop: "{{ mw_workstation_repositories }}"
