---
- name: Update apt packages
  become: true
  block:
    -
      name: Add Apt keys
      apt_key:
        url: "{{ item.url }}"
        id: "{{ item.id }}"
        state: present
      loop: "{{ workstation_apt_keys }}"
    -
      name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    -
      name: Install pip
      apt:
        update_cache: yes
        name:
          - python3-pip
          - dirmngr
        state: present
    -
      name: Install python apt
      pip:
        name: python-apt
        state: present
    -
      name: Add repositories
      apt_repository:
        repo: "{{ item.repo }}"
        codename: "{{ item.codename | d() }}"
      loop: "{{ workstation_repositories }}"
