---
- name: Converge
  hosts: all
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes
      become: true
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: "Include workstation_packages"
      include_role:
        name: "mw-workstation-packages"
