---
- name: Converge system packages
  hosts: system_packages
  roles:
    - role: mikroways.workstation
  vars:
    docker_service_manage: false
    workstation_tools_only: [kubectl, helm, krew]

- name: Converge tools
  hosts: tools
  tasks:
    - name: "Import only tools task from role"
      ansible.builtin.import_role:
        name: mikroways.workstation
        tasks_from: tools.yml
