---
# This is an example playbook to execute Ansible tests.

- name: Verify all packages
  hosts: all_local_packages
  gather_facts: true
  tasks:
    - name: "Include role vars"
      include_vars:
        dir: ../../defaults
        name: role_vars
    - name: "Verify installed packages"
      command: "{{ item.version_command }}"
      register: cmd
      failed_when: cmd.rc != 0 or item.version not in cmd.stdout
      changed_when: false
      environment:
        PATH: "{{ role_vars.mw_workstation_local_install_directory }}:{{ ansible_env.PATH }}"
      loop: "{{ role_vars.mw_workstation_local_packages }}"
      loop_control:
        label: "{{ item.name }} is version {{ item.version }}"
- name: Verify only some packages
  hosts: only_local_packages
  gather_facts: true
  tasks:
    - name: "Include role vars"
      include_vars:
        dir: ../../defaults
        name: role_vars
    - name: "Verify installed packages"
      command: "{{ item }}"
      register: cmd
      failed_when: cmd.rc != 0
      changed_when: false
      environment:
        PATH: "{{ role_vars.mw_workstation_local_install_directory }}:{{ ansible_env.PATH }}"
      loop: 
        - kubectl version --client --short
        - helm version --short
      loop_control:
        label: "{{ item.name }} is version {{ item.version }}"
