---
dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu-2204
    image: 'ubuntu:22.04'
lint: |
  set -ex
  yamllint .
  ansible-lint .
provisioner:
  name: ansible
verifier:
  name: ansible
